---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build
  pull: always
  image: spritsail/docker-build

  # Build again, this time with the newly 'just-built' image, as a test
- name: test
  pull: never
  image: ${DRONE_REPO_OWNER}/${DRONE_REPO_NAME}:${DRONE_STAGE_TOKEN}

- name: publish
  pull: always
  image: spritsail/docker-publish
  settings:
    repo: spritsail/docker-build
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  when:
    branch:
    - master
    event:
    - push

---
kind: signature
hmac: 396731229c00d147fb99cc9fda69c79928eef74fb48400a5d1070a60da5ec2e6

...
