pipeline:
  build:
    image: spritsail/docker-build
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    repo: spritsail/docker-build

  publish:
    image: spritsail/docker-publish
    when: { branch: [ master ], event: [ push, tag, deployment ] }
    volumes: [ '/var/run/docker.sock:/var/run/docker.sock' ]
    secrets: [ docker_username, docker_password, microbadger_token ]
    repo: spritsail/docker-build

  notify:
    image: appleboy/drone-telegram
    when: { status: [ success, failure ] }
    secrets: [ telegram_token, telegram_to ]
    message: |
      *{{repo.owner}}/{{repo.name}} [{{commit.branch}}]*: Build #{{build.number}}: *{{uppercase build.status}}*
      {{build.link}}
